import type { Dashboard } from "@/types/dashboard";

export const STARTER_PRESETS: Dashboard[] = [
  {
    id: "preset-system-overview",
    title: "Loza System Overview",
    description: "High-level overview of wide-event ingestion, error rates, service latency, and active hosts",
    tags: ["system", "overview", "core"],
    timeRange: "1h",
    isPreset: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    variables: [
      {
        id: "var-service",
        name: "service",
        label: "Service",
        type: "query",
        query: "from events | distinct service",
        defaultValue: "all",
        currentValue: "all",
        includeAll: true,
      },
      {
        id: "var-env",
        name: "environment",
        label: "Environment",
        type: "custom",
        options: ["all", "production", "staging", "dev"],
        defaultValue: "all",
        currentValue: "all",
        includeAll: true,
      },
    ],
    panels: [
      {
        id: "p-total-events",
        title: "Ingested Events",
        type: "stat",
        query: "from events | summarize count()",
        position: { x: 0, y: 0, w: 3, h: 3 },
        visualization: { unit: "count", color: "#3b82f6", sparkline: true },
      },
      {
        id: "p-error-rate",
        title: "Error Rate",
        type: "stat",
        query: 'from events | summarize count() by level | where level = "error" or level = "fatal"',
        position: { x: 3, y: 0, w: 3, h: 3 },
        visualization: {
          unit: "count",
          color: "#ef4444",
          thresholds: [
            { value: 0, color: "#10b981", label: "OK" },
            { value: 10, color: "#f59e0b", label: "Warning" },
            { value: 50, color: "#ef4444", label: "Critical" },
          ],
        },
      },
      {
        id: "p-p95-latency",
        title: "P95 Latency",
        type: "stat",
        query: "from events | summarize p95(duration_ms)",
        position: { x: 6, y: 0, w: 3, h: 3 },
        visualization: {
          unit: "ms",
          color: "#10b981",
          thresholds: [
            { value: 200, color: "#10b981" },
            { value: 500, color: "#f59e0b" },
            { value: 1000, color: "#ef4444" },
          ],
        },
      },
      {
        id: "p-active-services",
        title: "Active Services",
        type: "stat",
        query: "from events | summarize dcount(service)",
        position: { x: 9, y: 0, w: 3, h: 3 },
        visualization: { unit: "count", color: "#8b5cf6" },
      },
      {
        id: "p-throughput-timeseries",
        title: "Event Throughput Over Time",
        description: "Event ingestion rate binned into 5-minute intervals",
        type: "timeseries",
        query: "from events | summarize event_count = count() by bin(timestamp, 5m) | sort bin asc",
        position: { x: 0, y: 3, w: 8, h: 5 },
        visualization: { chartType: "area", color: "#3b82f6" },
      },
      {
        id: "p-level-breakdown",
        title: "Level Distribution",
        type: "pie",
        query: "from events | summarize count() by level",
        position: { x: 8, y: 3, w: 4, h: 5 },
        visualization: { showLegend: true },
      },
      {
        id: "p-top-errors-bar",
        title: "Errors by Service",
        type: "bar",
        query: 'from events | where level = "error" or level = "fatal" | summarize event_count = count() by service | sort event_count desc | take 10',
        position: { x: 0, y: 8, w: 6, h: 5 },
        visualization: { color: "#ef4444" },
      },
      {
        id: "p-recent-events-table",
        title: "Recent High-Severity Events",
        type: "table",
        query: 'from events | where level = "warn" or level = "error" or level = "fatal" | sort timestamp desc | take 25',
        position: { x: 6, y: 8, w: 6, h: 5 },
      },
    ],
  },
  {
    id: "preset-http-health",
    title: "HTTP API Health & Latency",
    description: "Request volumes, HTTP status code distribution (2xx/4xx/5xx), and latency percentiles",
    tags: ["http", "api", "latency"],
    timeRange: "1h",
    isPreset: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    variables: [
      {
        id: "var-service",
        name: "service",
        label: "Service",
        type: "query",
        query: "from events | distinct service",
        defaultValue: "all",
        currentValue: "all",
        includeAll: true,
      },
    ],
    panels: [
      {
        id: "p-http-req-volume",
        title: "Total HTTP Requests",
        type: "stat",
        query: "from events | where status_code > 0 | summarize count()",
        position: { x: 0, y: 0, w: 4, h: 3 },
        visualization: { unit: "count", color: "#3b82f6" },
      },
      {
        id: "p-5xx-rate",
        title: "5xx Server Error Rate",
        type: "gauge",
        query: "from events | where status_code >= 500 | summarize count()",
        position: { x: 4, y: 0, w: 4, h: 3 },
        visualization: {
          gaugeMin: 0,
          gaugeMax: 100,
          thresholds: [
            { value: 0, color: "#10b981" },
            { value: 5, color: "#f59e0b" },
            { value: 20, color: "#ef4444" },
          ],
        },
      },
      {
        id: "p-p99-latency",
        title: "P99 Response Time",
        type: "stat",
        query: "from events | summarize p99(duration_ms)",
        position: { x: 8, y: 0, w: 4, h: 3 },
        visualization: { unit: "ms", color: "#f59e0b" },
      },
      {
        id: "p-status-timeseries",
        title: "HTTP Status Code Trends",
        type: "timeseries",
        query: "from events | where status_code > 0 | summarize event_count = count() by status_code, bin(timestamp, 5m) | sort bin asc",
        position: { x: 0, y: 3, w: 8, h: 5 },
        visualization: { chartType: "line" },
      },
      {
        id: "p-slowest-routes",
        title: "Slowest Routes (P95 Latency)",
        type: "bar",
        query: 'from events | where route != "" | summarize p95_duration_ms = p95(duration_ms) by route | sort p95_duration_ms desc | take 8',
        position: { x: 8, y: 3, w: 4, h: 5 },
        visualization: { unit: "ms", color: "#f97316" },
      },
      {
        id: "p-failing-routes-table",
        title: "Recent 5xx Failures",
        type: "table",
        query: "from events | where status_code >= 500 | sort timestamp desc | take 20",
        position: { x: 0, y: 8, w: 12, h: 5 },
      },
    ],
  },
  {
    id: "preset-error-intelligence",
    title: "Error & Exception Intelligence",
    description: "Failure grouping, panic diagnostics, unhandled exceptions, and error fingerprinting",
    tags: ["errors", "exceptions", "panics"],
    timeRange: "24h",
    isPreset: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    variables: [
      {
        id: "var-service",
        name: "service",
        label: "Service",
        type: "query",
        query: "from events | distinct service",
        defaultValue: "all",
        currentValue: "all",
        includeAll: true,
      },
    ],
    panels: [
      {
        id: "p-error-types-bar",
        title: "Errors by Exception Type",
        type: "bar",
        query: 'from events | where level = "error" or level = "fatal" | summarize event_count = count() by error.type | sort event_count desc | take 10',
        position: { x: 0, y: 0, w: 6, h: 5 },
        visualization: { color: "#ef4444" },
      },
      {
        id: "p-error-services-pie",
        title: "Failing Services Distribution",
        type: "pie",
        query: 'from events | where level = "error" or level = "fatal" | summarize count() by service',
        position: { x: 6, y: 0, w: 6, h: 5 },
        visualization: { showLegend: true },
      },
      {
        id: "p-unhandled-panics-table",
        title: "Unhandled Panics & Exceptions",
        type: "table",
        query: 'from events | where error.stack != "" | sort timestamp desc | take 25',
        position: { x: 0, y: 5, w: 12, h: 6 },
      },
    ],
  },
  {
    id: "preset-collector-infra",
    title: "Collector Infrastructure",
    description: "Collector ingest performance, DLQ buffers, sink health, and real-time live tail",
    tags: ["collector", "infrastructure", "sinks"],
    timeRange: "1h",
    isPreset: true,
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    variables: [],
    panels: [
      {
        id: "p-collector-throughput",
        title: "Collector Ingest Rate",
        type: "stat",
        query: "from events | summarize count()",
        position: { x: 0, y: 0, w: 6, h: 3 },
        visualization: { unit: "count", color: "#10b981" },
      },
      {
        id: "p-dlq-count",
        title: "Quarantined / DLQ Events",
        type: "stat",
        query: 'from events | where outcome = "quarantined" or outcome = "rejected" | summarize count()',
        position: { x: 6, y: 0, w: 6, h: 3 },
        visualization: { unit: "count", color: "#ef4444" },
      },
      {
        id: "p-collector-live-stream",
        title: "Live Event Tail Stream",
        type: "logstream",
        query: "from events | take 100",
        position: { x: 0, y: 3, w: 12, h: 7 },
      },
    ],
  },
];

export function exportDashboardJson(dashboard: Dashboard): string {
  return JSON.stringify(dashboard, null, 2);
}

export function importDashboardJson(jsonString: string): Dashboard {
  const parsed = JSON.parse(jsonString) as Partial<Dashboard>;
  if (!parsed.title || !Array.isArray(parsed.panels)) {
    throw new Error("Invalid dashboard JSON format: missing title or panels array");
  }

  return {
    id: "dash-" + Math.random().toString(36).substring(2, 9),
    title: parsed.title,
    description: parsed.description || "",
    tags: parsed.tags || [],
    timeRange: parsed.timeRange || "1h",
    variables: parsed.variables || [],
    panels: parsed.panels.map((p, idx) => ({
      id: p.id || `panel-${idx + 1}`,
      title: p.title || "Untitled Panel",
      description: p.description,
      type: p.type || "timeseries",
      query: p.query || "from events | limit 100",
      content: p.content,
      position: p.position || { x: (idx % 2) * 6, y: Math.floor(idx / 2) * 4, w: 6, h: 4 },
      visualization: p.visualization,
    })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    isPreset: false,
  };
}
